POST http://localhost:3000/api/items
Content-Type: application/json

{
    "name": "Pia",
    "place": "Cozinha"
}

###
GET http://localhost:3000/api/items

###
DELETE http://localhost:3000/api/items/6571d8f2e7ee74ba247a6185